### ISSUE TITLE
能加一个好友么

### ISSUE THREAD

**Issue by edsky** [yqsy/yqsy.notes#1]
想交流一下ai

**Comment by yqsy** [comment]
啥意思？

Sent from Mail for Windows 10

From: edsky
Sent: 2020年7月9日 21:33
To: yqsy/yqsy.notes
Cc: Subscribed
Subject: [yqsy/yqsy.notes] 能加一个好友么 (#1)

想交流一下ai

**Comment by edsky** [comment]
我的邮箱是 dead.ash@hotmail.com， 给我发一个邮件你的qq，加qq交流一下，有些思路想探讨一下

**Comment by yqsy** [comment]
你把你的qq发给我

Sent from Mail for Windows 10

**Comment by edsky** [comment]
qq: 773535502
